#!/bin/bash

echo "########################"
echo "Installing packages"
echo
sudo yum install httpd wget unzip -y >/dev/null
echo

echo "########################'
echo "start and enable httpd service'
sudo systemctl start httpd
sudo systemctl enable httpd
echo

echo "#######################"
echo "Artifact deployment"
mkdir /tmp/webfiles
cd /tmp/webfiles
echo

echo"#######################'
